[tool.poetry]
name = "convert_url"
version = "0.1.0"
description = ""
authors = ["FloowDot <eli.chandlerr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
